#!/bin/bash

if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then
  echo >&2 "ERROR: This script needs to be sourced to run correctly"
  exit 1
fi

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
${script_dir}/lib/setup_venv.sh

. ${script_dir}/lib/get_credentials.sh AO_MIKROTIK_CREDENTIALS

"${HOME}/.cache/venv/mikrotik-tools-py3/bin/python3" \
  ${script_dir}/lib/download_config.py "$@"
